apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: argocd-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:bL3rXSMGzoVn/aogO7Aug1ZKhJ9727bU9gGuN1IEidcmbkLtbGBYIQ8JXqt0bpVtjuhxJmXpeLLSSRtDkZu/cZRzcL8JpDJMaHU=,iv:WB3flhT78UpSmJIkl1gW3enHJFke73iu6JiWmV03DTA=,tag:qenUwX9+ZlmFWBcgedMHsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T17:49:52Z"
    mac: ENC[AES256_GCM,data:JGrJPMij15k3ti9L8pjbYsgHeTColKEQ0JeMIKlUTzPI9HYAQbn4E9fgk+rJqvxYcU6WTZrjbxB3UcmDpapAw+6q+/CJx3qiilVzTYdZ695XJtzo/viflWFZcQxLKFdkzOH22JfCSwky9tDx0Ha7jHbVZzm4G5nMArtmnWgq92A=,iv:Bpjfqa5qvQv2CgfB1IxdO7RgeE8HhXy3P2LZpfM5Ppo=,tag:mRPLWKAmTpGjhrsiue/XDg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
