apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager-system
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:KUIQiZH2YUPWSXCovCauA94FqYfrockeUGapSissWlJTt8OeFNvqbg==,iv:P30tQ6JPtE7EUXmDo0qUB3xP0qPZlFL20VXDAyrtWCE=,tag:5ZPKLQQVF/mm+VtOnEr6qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSHNCbWRkeTRWVEhiRDdN
            ZS92NHc1QVZaZjdjTW1MWW04RXphZnBoa0U4CkFNbDFNbmZOekEvcFpiM1RUMUl2
            R096OTNnenFoNlgxUC9qV0hwREVJdFUKLS0tICtMS3NkU0x5RVFnaHBGK2Z3VmU3
            ekg5SjZZU1daT2N3TUF2ZFZmUXF1YkEK7m/TcmqXmr7xxID2wNBP62cXtgWILUkt
            XAO9Y3u0CdT8eMUWQuASJqDXuN+Zb9KEDDs6+z9CGtCJ/yqXBlFWTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T17:48:33Z"
    mac: ENC[AES256_GCM,data:B+xSM5+IAQtSS6UDL+DZeEMeYCfR9NOkG2uKcdkVDzgDP+DB1KP3UglUmpLD69ls8oEjxn6jmxjjKJxY/l3ro/P/EEuM0gCy7j89S7Ul4hwDpTkSQX9ly5h/waD5fO3iqBIcFl6DvX8NZH15gf0iGf5TjP26VJc00/xPms2ZYoo=,iv:hebjySIrLYx8P4q5ahhmVAwwjYhXdzm0NXEXG+crNcE=,tag:2GIOmXWidL6aNoXRU0gfMQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
