apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: default
type: Opaque
stringData:
    SERVICE_DOMAIN: ENC[AES256_GCM,data:yHEz6xdLiL4Ozbyp,iv:P3ANJSyHJWnT7OlCifqCZXzVsNnuFMWVAitVT08+mWU=,tag:KRqlMufETEejv28fASHcMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T12:40:36Z"
    mac: ENC[AES256_GCM,data:l0soFU04RnC/dI4hbQ0kc4OvbSilhtmNy9GyGW9BGxiMCoC4xoJnHdsYfugstZYDFf2g4ZoJEdYDfgmR7dc8Kt8wNolTw0UHv3S/aoLmYuJfLj2t22C3WbJrF164+DsXGLh8pfLW4SeS9GoXzODPvcbFDLBkdSpJ7jgUmgkEyXo=,iv:Hy3FnZAxOEuvAFQFNJ+dLiydYBJ0esluaDA/Un4qo7M=,tag:Z0xIOm8PUgX/J9i7xbgGkQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xmjv8ZQ=,iv:ZfK0gtYh1sAAV+kgEzySQlQbB1lFcr/Ky+giUMXfUZE=,tag:dtE7pZ2HB33J/Q380O/s8A==,type:str]
    password: ENC[AES256_GCM,data:3SFvNcNOegNReeqlUNolfA8/FxK8jEhNKM3iF8mF+Tk=,iv:uzalyrOL0HWu/xik6Guuv6gdDE/gBosqVjUg8xqtSak=,tag:cfZydrZs3lcCsa20EJ4spw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T12:40:36Z"
    mac: ENC[AES256_GCM,data:l0soFU04RnC/dI4hbQ0kc4OvbSilhtmNy9GyGW9BGxiMCoC4xoJnHdsYfugstZYDFf2g4ZoJEdYDfgmR7dc8Kt8wNolTw0UHv3S/aoLmYuJfLj2t22C3WbJrF164+DsXGLh8pfLW4SeS9GoXzODPvcbFDLBkdSpJ7jgUmgkEyXo=,iv:Hy3FnZAxOEuvAFQFNJ+dLiydYBJ0esluaDA/Un4qo7M=,tag:Z0xIOm8PUgX/J9i7xbgGkQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
