apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://twin.github.io/helm-charts
      chart: gatus
      targetRevision: 1.1.0
      helm:
        valuesObject:
          image:
            repository: ghcr.io/twin/gatus
            tag: v5.15.0
            sha: 45686324db605e57dfa8b0931d8d57fe06298f52685f06aa9654a1f710d461bb
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            path: /
            pathType: Prefix
            hosts:
              - gatus.kthxbye.cyou
            tls:
              - secretName: gatus-tls
                hosts:
                  - gatus.kthxbye.cyou
          # desperately waiting for https://github.com/TwiN/helm-charts/pull/18
          config:
            endpoints:
              - name: gatus
                url: https://gatus.kthxbye.cyou
                interval: 60s
                conditions:
                  - "[STATUS] == 200"
  destination:
    name: in-cluster
    namespace: default
