apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://helm.irsigler.cloud
      chart: uptime-kuma
      targetRevision: 2.21.2
      helm:
        valuesObject:
          image:
            repository: louislam/uptime-kuma
            tag: 1.23.16-alpine@sha256:f111cca721507faa0a57e1ffc75210d64c9a9ca0f8375e0336a2a9a88ae2987c
          ingress:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
              nginx.ingress.kubernetes.io/server-snippets: |
                location / {
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_http_version 1.1;
                  proxy_set_header X-Forwarded-Host $http_host;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-Forwarded-For $remote_addr;
                  proxy_set_header Host $host;
                  proxy_set_header Connection "upgrade";
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header   Upgrade $http_upgrade;
                  proxy_cache_bypass $http_upgrade;
                }
            hosts:
              - host: uptime-kuma.kthxbye.cyou
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - secretName: uptime-kuma-tls
                hosts:
                  - uptime-kuma.kthxbye.cyou
          volume:
            enabled: false
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
